### ISSUE TITLE
Magic number

### ISSUE THREAD

**Issue by daisy-ua** [1Mayuko1/Euro_Diffusion#1]
https://github.com/1Mayuko1/Euro_Diffusion/blob/f0f43195365a01390c115fce2748ad76dce98c90/lab1.js#L187-L204

Using magic numbers can  make the code difficult to understand and maintain. Please consider changing it to const.

**Comment by daisy-ua** [comment]
https://github.com/1Mayuko1/Euro_Diffusion/blob/f0f43195365a01390c115fce2748ad76dce98c90/lab1.js#L70
Same here - please change to const

**Comment by 1Mayuko1** [comment]
Thanks, alrerady fixed
