### ISSUE TITLE
Const

### ISSUE THREAD

**Issue by IanaKhitsko** [1Mayuko1/Euro_Diffusion#4]
https://github.com/1Mayuko1/Euro_Diffusion/blob/ab960c6015d6733bcdc82b7bc5bc59ef48cdaa51/lab1.js#LL114C38-L114C45

Consider using const

**Comment by IanaKhitsko** [comment]
and here https://github.com/1Mayuko1/Euro_Diffusion/blob/ab960c6015d6733bcdc82b7bc5bc59ef48cdaa51/lab1.js#L132

**Comment by IanaKhitsko** [comment]
https://github.com/1Mayuko1/Euro_Diffusion/blob/ab960c6015d6733bcdc82b7bc5bc59ef48cdaa51/lab1.js#LL237C34-L237C40

**Comment by 1Mayuko1** [comment]
The problem has been solved, thanks for the comment
